server:
  port: 8080
  servlet:
    context-path: /pa
spring:
  datasource:
    username:
    password:
    url:
    driver-class-name: org.mariadb.jdbc.Driver

sftp:
  host:
  port:
  user:
  password:
  path: "/pa-test/"
logging:
  file:
    name: "./log/Han-engin.log"
  logback:
    rollingpolicy:
      max-file-size: 100MB
  level:
    root: info
    com:
      crater:
        hanaengine:
          dao:
            mapper: debug
